blank_issues_enabled: true
contact_links:
  - name: Tiger Support
    url: https://t.me/TigerNetworkChat
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://Tiger.tech/
    about: Documentation for getting started with bot.
